DROP DATABASE IF EXISTS `evalution_system`;

CREATE DATABASE `evalution_system`;
USE `evalution_system`;

DROP TABLE IF EXISTS `CLASS_STUDENT`;
DROP TABLE IF EXISTS `EVALUTION`; 
DROP TABLE IF EXISTS `CLASS_INFO`;
DROP TABLE IF EXISTS `USER_STUDENT`;
DROP TABLE IF EXISTS `USER_TEACHER`;
DROP TABLE IF EXISTS `USER_ADMIN`;
DROP TABLE IF EXISTS `STU_INFO`;
DROP TABLE IF EXISTS `TEA_INFO`;
DROP TABLE IF EXISTS `TABLE_CHANGE_LOG`;
DROP PROCEDURE IF EXISTS SELECT_TABLE_CHANGE_LOG;

CREATE TABLE `STU_INFO` (
  `STU_ID` int(11) NOT NULL AUTO_INCREMENT,
  `STU_NAME` varchar(255) NOT NULL,
  `STU_PASSWORD` varchar(255) NOT NULL,
  `FLAG` int(1) not null DEFAULT 0,
  PRIMARY KEY (`STU_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `TEA_INFO` (
  `TEA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TEA_NAME` varchar(255) NOT NULL,
  `TEA_PASSWORD` varchar(255) NOT NULL,
  PRIMARY KEY (`TEA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `TABLE_CHANGE_LOG` (
  `CHANGE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `IS_CHANGED` int(11) NOT NULL,
  PRIMARY KEY (`CHANGE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `USER_STUDENT` (
  `USER_STU_ID` int(11) NOT NULL,
  `STUDENT_NAME` varchar(255) NOT NULL,
  `STUDENT_NICKNAME` varchar(255) NOT NULL,
  `STUDENT_PASSWORD` varchar(255) NOT NULL,
  PRIMARY KEY (`USER_STU_ID`),
  FOREIGN KEY (`USER_STU_ID`) REFERENCES `STU_INFO`(`STU_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `USER_TEACHER` (
  `TEACHER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TEACHER_NAME` varchar(255) NOT NULL,
  `TEACHER_PASSWORD` varchar(255) NOT NULL,
  PRIMARY KEY (`TEACHER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `USER_ADMIN` (
  `ADMIN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADMIN_NAME` varchar(255) NOT NULL,
  `ADMIN_PASSWORD` varchar(255) NOT NULL,
  PRIMARY KEY (`ADMIN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `CLASS_INFO` (
  `CLASS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CLASS_NAME` varchar(255) NOT NULL,
  `CLASS_TEACHER_ID` int(11) NOT NULL,
  PRIMARY KEY (`CLASS_ID`),
  FOREIGN KEY (`CLASS_TEACHER_ID`) REFERENCES `USER_TEACHER`(`TEACHER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `EVALUTION` (
  `EVALUTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `STUDENT_ID` int(11) NOT NULL,
  `CLASS_ID` int(11) NOT NULL,
  `EMOJI_CODE` varchar(255) NOT NULL,
  `EVALUTION_DATE` datetime NOT NULL,
  PRIMARY KEY (`EVALUTION_ID`),
  FOREIGN KEY (`STUDENT_ID`) REFERENCES `USER_STUDENT`(`USER_STU_ID`),
  FOREIGN KEY (`CLASS_ID`) REFERENCES `CLASS_INFO`(`CLASS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `CLASS_STUDENT` (
  `CLASS_STUDENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CLASS_ID` int(11) NOT NULL,
  `STU_ID` int(11) NOT NULL,
  PRIMARY KEY (`CLASS_STUDENT_ID`),
  FOREIGN KEY (`CLASS_ID`) REFERENCES `CLASS_INFO`(`CLASS_ID`),
  FOREIGN KEY (`STU_ID`) REFERENCES `STU_INFO`(`STU_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


INSERT INTO `TABLE_CHANGE_LOG` (`IS_CHANGED`) VALUES (0);

INSERT INTO `STU_INFO` (`STU_NAME`, `STU_PASSWORD`, `FLAG`) VALUES ('Leo', '123456', '1');
INSERT INTO `STU_INFO` (`STU_NAME`, `STU_PASSWORD`, `FLAG`) VALUES ('咒仕', '123456', '0');
INSERT INTO `STU_INFO` (`STU_NAME`, `STU_PASSWORD`, `FLAG`) VALUES ('雪象', '123456', '0');
INSERT INTO `STU_INFO` (`STU_NAME`, `STU_PASSWORD`, `FLAG`) VALUES ('玄马', '123456', '0');
INSERT INTO `STU_INFO` (`STU_NAME`, `STU_PASSWORD`, `FLAG`) VALUES ('池车', '123456', '0');
INSERT INTO `STU_INFO` (`STU_NAME`, `STU_PASSWORD`, `FLAG`) VALUES ('雷炮', '123456', '0');
INSERT INTO `STU_INFO` (`STU_NAME`, `STU_PASSWORD`, `FLAG`) VALUES ('铁卒', '123456', '0');

INSERT INTO `USER_STUDENT` (`USER_STU_ID`, `STUDENT_NAME`, `STUDENT_NICKNAME`, `STUDENT_PASSWORD`) VALUES ('1', 'Leo', '沧月', '123');

INSERT INTO `USER_TEACHER` (`TEACHER_NAME`, `TEACHER_PASSWORD`) VALUES ('岡田紗佳', '123456');
INSERT INTO `USER_TEACHER` (`TEACHER_NAME`, `TEACHER_PASSWORD`) VALUES ('高宮 まり', '123456');
INSERT INTO `USER_TEACHER` (`TEACHER_NAME`, `TEACHER_PASSWORD`) VALUES ('瑞原明奈', '123456');

INSERT INTO `CLASS_INFO` (`CLASS_NAME`, `CLASS_TEACHER_ID`) VALUES ('Maj', 1);
INSERT INTO `CLASS_INFO` (`CLASS_NAME`, `CLASS_TEACHER_ID`) VALUES ('Elden Ring', 1);
INSERT INTO `CLASS_INFO` (`CLASS_NAME`, `CLASS_TEACHER_ID`) VALUES ('Maj', 2);
INSERT INTO `CLASS_INFO` (`CLASS_NAME`, `CLASS_TEACHER_ID`) VALUES ('Genshin Impact', 2);
INSERT INTO `CLASS_INFO` (`CLASS_NAME`, `CLASS_TEACHER_ID`) VALUES ('Maj', 3);
INSERT INTO `CLASS_INFO` (`CLASS_NAME`, `CLASS_TEACHER_ID`) VALUES ('Dark Souls III', 3);

INSERT INTO `USER_ADMIN` (`ADMIN_NAME`, `ADMIN_PASSWORD`) VALUES ('Admin', '123456');

INSERT INTO `EVALUTION` (`STUDENT_ID`, `CLASS_ID`, `EMOJI_CODE`, `EVALUTION_DATE`) VALUES (1, 1, 'U+1F60D', '2020-01-01 00:00:00');
INSERT INTO `EVALUTION` (`STUDENT_ID`, `CLASS_ID`, `EMOJI_CODE`, `EVALUTION_DATE`) VALUES (1, 2, 'U+1F60D', '2020-01-01 00:00:00');
INSERT INTO `EVALUTION` (`STUDENT_ID`, `CLASS_ID`, `EMOJI_CODE`, `EVALUTION_DATE`) VALUES (1, 3, 'U+1F60D', '2020-01-01 00:00:00');
INSERT INTO `EVALUTION` (`STUDENT_ID`, `CLASS_ID`, `EMOJI_CODE`, `EVALUTION_DATE`) VALUES (1, 4, 'U+1F60D', '2020-01-01 00:00:00');
INSERT INTO `EVALUTION` (`STUDENT_ID`, `CLASS_ID`, `EMOJI_CODE`, `EVALUTION_DATE`) VALUES (1, 5, 'U+1F60D', '2020-01-01 00:00:00');
INSERT INTO `EVALUTION` (`STUDENT_ID`, `CLASS_ID`, `EMOJI_CODE`, `EVALUTION_DATE`) VALUES (1, 6, 'U+1F60D', '2020-01-01 00:00:00');

INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (1, 1);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (2, 1);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (3, 1);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (4, 1);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (5, 1);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (6, 1);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (1, 2);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (2, 2);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (3, 2);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (4, 2);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (5, 2);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (6, 2);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (1, 3);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (2, 3);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (3, 3);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (4, 3);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (5, 3);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (6, 3);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (1, 4);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (2, 4);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (3, 4);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (4, 4);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (5, 4);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (6, 4);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (1, 5);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (2, 5);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (3, 5);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (4, 5);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (5, 5);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (6, 5);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (1, 6);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (2, 6);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (3, 6);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (4, 6);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (5, 6);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (6, 6);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (1, 7);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (2, 7);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (3, 7);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (4, 7);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (5, 7);
INSERT INTO `CLASS_STUDENT` (`CLASS_ID`, `STU_ID`) VALUES (6, 7);



DELIMITER //
CREATE PROCEDURE SELECT_TABLE_CHANGE_LOG()
BEGIN
  SELECT IS_CHANGED FROM TABLE_CHANGE_LOG WHERE CHANGE_ID = 1;
  UPDATE TABLE_CHANGE_LOG SET IS_CHANGED = 0 WHERE CHANGE_ID = 1;
END //
DELIMITER ;

drop table if exists images;
CREATE TABLE images 
(
	TEACHER_ID            int(20)                       not null,
	image_path VARCHAR(255)
);

INSERT INTO `images` (`TEACHER_ID`, `image_path`) VALUES ('1', '../static/images/1.jpg');
INSERT INTO `images` (`TEACHER_ID`, `image_path`) VALUES ('2', '../static/images/2.jpg');
INSERT INTO `images` (`TEACHER_ID`, `image_path`) VALUES ('3', '../static/images/3.jpg');

DROP EVENT IF EXISTS `RESET_TABLE_CHANGE_LOG`;
CREATE EVENT RESET_TABLE_CHANGE_LOG 
ON SCHEDULE EVERY 10 SECOND
DO
  UPDATE TABLE_CHANGE_LOG SET IS_CHANGED = 0 WHERE CHANGE_ID = 1;
